ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'ADMIN';
CREATE TYPE "UserAccountStatus" AS ENUM ('PENDING', 'ACTIVE', 'BLOCKED');
ALTER TABLE "User" ADD COLUMN "accountStatus" "UserAccountStatus" NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE "User" ALTER COLUMN "accountStatus" SET DEFAULT 'PENDING';
